config/routes.rb
require 'resque/server'
Emmy::Application.routes.draw do
  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'

  mount Resque::Server.new, at: "/resque"

  root 'pages#start'
  devise_for :users, controllers: {sessions: 'user_sessions'}
  [:about, :start, :formats, :test].each do |p|
    get "/#{p}", to: "pages##{p}"
  end

  namespace :admin do
    resources :organizations
    resources :users do
      member do
        patch 'update_roles', as: :update_roles
      end
    end
    get 'dashboard', to: 'dashboard#index'
    constraints lambda { |request| request.env['warden'].authenticate? && request.env['warden'].user.superadmin? } do
      mount Resque::Server.new, at: "resque"
    end
  end

  get "organization_selector", to: "dashboard#organization_selector"
  get ':organization_slug', to: 'organizations#show', as: 'organization'
  patch ':organization_slug', to: 'organizations#update'
  scope ':organization_slug' do
    get "dashboard", to: "dashboard#index"

    resources :accounting_periods

    resources :accounting_plans do
      post 'disable_accounts', as: :disable_accounts
      resources :accounting_groups
      resources :accounting_classes
      resources :accounts do
        post 'toggle_active', as: :toggle_active
      end
    end
    get 'accounts_receivables', to: 'accounts_receivables#index', as: 'accounts_receivables'
    get 'accounts_payables', to: 'accounts_payables#index', as: 'accounts_payables'
    resources :batches
    resources :closing_balances do
      resources :closing_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :comments
    resources :contact_relations
    resources :contacts
    resources :conversions do
      delete 'clear'
    end
    resources :customers do
      collection do
        get 'name_search', as: :name_search
        get 'city_search', as: :city_search
      end
    end
    resources :default_codes
    resources :default_code_headers
    resources :documents
    resources :employees
    resources :export_bank_files
    resources :economics_wizard do
      collection do
        get 'start'
        get 'stop'
      end
    end
    resources :export_bank_file_rows
    get 'helps/show_help'
    get 'helps/show_chapter_help'
    get 'helps/show_message'
    resources :import_bank_files do
      resources :import_bank_file_rows do
        get 'match_verificate', as: :match_verificate
        get 'set_verificate', as: :set_verificate
        get 'set_template_verificate', as: :set_template_verificate
      end
    end
    resources :import_batches, only: [:new, :create]
    resources :imports do
      resources :import_batches, only: [:new, :create]
      member do
        post 'state_change', as: :state_change
        get 'new_purchase', as: :new_purchase
        post 'create_purchase', as: :create_pruchase
      end
    end
    resources :ink_code_headers
    resources :ink_codes
    resources :inventories do
      resources :inventory_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :items
    resources :ledgers do
      resources :ledger_accounts
    end
    resources :ledger_transactions
    resources :manuals
    resources :mail_templates
    resources :materials
    resources :ne_code_headers
    resources :ne_codes
    resources :opening_balances do
      post 'create_from_ub'
      resources :opening_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :production_batches, only: [:new, :create]
    resources :productions do
      resources :production_batches, only: [:new, :create]
      resources :materials
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :purchases do
      resources :purchase_items
      member do
        post 'state_change', as: :state_change
      end
      post 'single_purchase', as: :single_purchase
    end

    get 'reports/order_verificates_report'
    get 'reports/order_ledger_report'
    get 'reports/order_result_report'
    get 'reports/order_balance_report'
    get 'reports/sale_statistics'
    post 'reports/verificates'
    post 'reports/ledger'
    post 'reports/result_report'
    post 'reports/balance_report'

    resources :result_units

    resources :reversed_vats do
      resources :reversed_vat_reports
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :sales do
      resources :sale_items
      member do
        post 'state_change', as: :state_change
        post 'send_email', as: :send_email
        post 'send_reminder_email', as: :send_reminder_email
        post 'regenerate_invoice', as: :regenerate_invoice
      end
      collection do
        get 'invoice_search', as: :invoice_search
      end
    end
    get 'statistics/index'
    resources :shelves

    resources :sie_exports
    resources :sie_imports

    resources :simplified_sales

    resources :suppliers

    resources :stock_values do
      resources :stock_value_items
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :tax_code_headers
    resources :tax_codes

    resources :tax_returns do
      resources :tax_return_reports
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :tax_tables do
      resources :tax_table_rows
    end

    post 'templates_import', to: 'templates#import', as: 'templates_import'
    resources :templates do
      resources :template_items
    end

    resources :transfers do
      member do
        post 'send_package', as: :send_package
        post 'receive_package', as: :receive_package
      end
    end
    resources :units
    resources :users do
      member do
        patch :update_roles, as: :update_roles
      end
    end
    resources :vat_periods do
      resources :vat_reports
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :vats
    resources :verificates do
      resources :verificate_items
      member do
        post 'state_change', as: :state_change
        post 'reversal', as: :reversal
        post 'add_verificate_items', as: :add_verificate_items
      end
    end
    resources :wage_periods do
      resources :wages
      resources :wage_reports
      member do
        post 'state_change', as: :state_change
        post 'create_wage', as: :create_wage
      end
    end
    resources :wages_wizard do
      collection do
        get 'start'
        get 'stop'
      end
    end
    resources :warehouses
  end

end

app/models/wage.rb
class Wage < ActiveRecord::Base
  # t.datetime :wage_from
  # t.datetime :wage_to
  # t.datetime :payment_date
  # t.decimal  :salery
  # t.decimal  :addition
  # t.decimal  :discount
  # t.decimal  :tax
  # t.decimal  :payroll_tax
  # t.decimal  :amount
  # t.integer  :organization_id
  # t.integer  :accounting_period_id
  # t.integer  :wage_period_id
  # t.integer  :employee_id

  #attr_accessible :employee_id, :wage_from, :wage_to, :payment_date, :salary, :addition, :discount,
  #                :tax, :payroll_tax, :amount, :wage_period_id, :accounting_period_id

  belongs_to :organization
  belongs_to :accounting_period
  belongs_to :wage_period
  belongs_to :employee
  has_one :verificate
  has_one :document, as: :parent, dependent: :destroy

  before_save :set_payroll_tax
  before_save :set_tax
  before_save :set_amount

  validates :accounting_period, presence: true
  validates :employee, presence: true
  validates :wage_from, presence: true
  validates :wage_to, presence: true
  validates :payment_date, presence: true

  scope :by_year, ->(year) { where("payment_date >= ? AND payment_date <= ?",
                                   year.beginning_of_year, year.end_of_year) }

  def set_document(name, pdf_string)
    logger.info "-------------- Wage#set_document: will try to write to temp file id #{self.id}"
    begin
      d = build_document
      tempfile = Tempfile.new([name, '.pdf'], Rails.root.join('tmp'))
      tempfile.binmode
      tempfile.write pdf_string
      d.upload = tempfile
      d.save!
    rescue Exception => e
        logger.info "-------------- wage#set_document failed: #{e} : #{e.message}"
        raise e
    ensure
      tempfile.close!
    end
    logger.info 'Wage#set_document: SAVING!'
  end

  def gross
    salary + addition - discount
  end

  def set_payroll_tax
    self.payroll_tax = (gross * employee.payroll_percent).round
  end

  def set_tax
    self.tax = employee.tax_table.calculate(gross, employee.tax_table_column)
  end

  def set_amount
    self.amount = gross - tax
  end

  def has_document?
    return false if document.nil?
    return true
  end

  def can_delete?
    return true if wage_period.can_calculate_wage?
    false
  end
end

app/controllers/wages_controller.rb
class WagesController < ApplicationController
  respond_to :html, :json
  load_and_authorize_resource :wage_period, through: :current_organization
  load_and_authorize_resource :wage, through: :current_organization

  before_action :new_breadcrumbs, only: [:new, :create]
  before_action :show_breadcrumbs, only: [:edit, :show, :update]

  # GET /wages
  # GET /wages.json
  def index
    @breadcrumbs = [[t(:wage_periods), wage_periods_path],
                    [@wage_period.name, wage_period_path(@wage_period.id)],
                    [t(:wages)]]
    @wage_periods = current_organization.wage_periods.order('id')
    if !params[:wage_period_id] && @wage_periods.count > 0
      params[:wage_period_id] = @wage_periods.first.id
    end
    @wages = current_organization.wages.where('wage_period_id=?', params[:wage_period_id])
    @wages = @wages.page(params[:page]).decorate
  end

  # GET /wages/new
  def new
    @wage.accounting_period_id = @wage_period.accounting_period_id
    @wage.wage_period_id = @wage_period.id
    @wage.wage_from = @wage_period.wage_from
    @wage.wage_to = @wage_period.wage_to
    @wage.payment_date = @wage_period.payment_date
    @wage.salary = 0
    @wage.addition = 0
    @wage.discount = 0
    @employees = current_organization.employees
  end

  # GET /wages/1
  def show
    respond_to do |format|
      format.html
      format.pdf do
        send_file(@wage.document.upload.path,
                  filename: "spec_#{@wage.id}.pdf",
                  type: 'application/pdf')
      end
    end
  end

  # GET /wage/1/edit
  def edit
    @employees = current_organization.employees
  end

  # POST /wages
  # POST /wages.json
  def create
    @wage = Wage.new(wage_params)
    @wage.organization = current_organization
    respond_to do |format|
      if @wage.save
        format.html { redirect_to wage_period_wages_path, notice: "#{t(:wage)} #{t(:was_successfully_created)}" }
      else
        @employees = current_organization.employees
        flash.now[:danger] = "#{t(:failed_to_create)} #{t(:wage)}"
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @wage.update(wage_params)
        format.html { redirect_to wage_period_wages_path, notice: "#{t(:wage)} #{t(:was_successfully_updated)}" }
      else
        @employees = current_organization.employees
        flash.now[:danger] = "#{t(:failed_to_update)} #{t(:wage)}"
        format.html { render action: 'show' }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @wage.destroy
    respond_to do |format|
      format.html { redirect_to wage_period_wages_path, notice: "#{t(:wage)} #{t(:was_successfully_deleted)}" }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def wage_params
    params.require(:wage).permit(:employee_id, :wage_from, :wage_to, :payment_date, :salary, :addition,
                                 :discount, :tax, :payroll_tax, :amount, :wage_period_id, :accounting_period_id)
  end

  def new_breadcrumbs
    @breadcrumbs = [[t(:wage_periods), wage_periods_path],
                    [@wage_period.name, wage_period_path(@wage_period.id)],
                    [t(:wages), wage_period_wages_path],
                    [t(:wage)]]
  end

  def show_breadcrumbs
    @breadcrumbs = [[t(:wage_periods), wage_periods_path],
                    [@wage.wage_period.name, wage_period_path(@wage.wage_period_id)],
                    [t(:wages), wage_period_wages_path(@wage.wage_period_id)],
                    [@wage.employee.name]]
  end
end

app/views/wages/_form.html.haml
= simple_form_for([@wage_period, @wage], wrapper: :horizontal_form, html: {class: 'form-horizontal'}) do |f|
  = f.error_notification
  = f.input :accounting_period_id, as: :hidden
  = f.input :wage_period_id, as: :hidden
  = f.association :employee, collection: @employees, disabled: !@wage.new_record?

  .form-group.form-inline
    .labels_width.control-label
      = f.label :wage_from
    .fields_width
      = f.date_field :wage_from
      = f.error :wage_from

  .form-group.form-inline
    .labels_width.control-label
      = f.label :wage_to
    .fields_width
      = f.date_field :wage_to
      = f.error :wage_to

  .form-group.form-inline
    .labels_width.control-label
      = f.label :payment_date
    .fields_width
      = f.date_field :payment_date
      = f.error :payment_date

  = f.input :salary
  = f.input :addition
  = f.input :discount
  = f.input :tax, disabled: true
  = f.input :amount, disabled: true
  = f.input :payroll_tax, disabled: true

  - if @wage.new_record? || @wage.can_delete?
    .form-button-group
      .actions
        = f.submit class: 'btn btn-primary'

app/views/wages/_list.html.haml
- year = DateTime.now
- year = DateTime.new(params[:year].to_i) if params[:year].present?
- wage_years = []
- wages.each do |wage|
  - payment_year = wage.payment_date.year
  - if !wage_years.include? payment_year
    - wage_years.push(payment_year)
- wages = wages.by_year(year).page(params[:page]).decorate

.row
  .col-sm-40.col-md-40.pull-right.text-right
    = form_tag employee_path(employee), class: 'form-inline submit-on-change', method: :get, enforce_utf8: false do
      = text_field_tag('locale' , params[:locale], type:'hidden')

      = select_tag("year",
        options_for_select(wage_years, year.year),
        class: 'btn btn-default')

.table-responsive
  %table{:class => 'table table-striped'}
    %thead
      %tr
        %th= t(:from)
        %th= t(:to)
        %th= t(:payment_date)
        %th= t(:salary)
        %th.numeric= t(:tax)
        %th.numeric= t(:amount)
        %th
    %tbody
      - wages.each do |wage|
        %tr
          %td= wage.wage_from
          %td= wage.wage_to
          %td= wage.payment_date
          %td= wage.salary
          %td.numeric= wage.tax
          %td.numeric= wage.amount
          %td
            - if wage.has_document?
              = link_to doc_icon, wage_period_wage_path(wage.wage_period, wage, format: 'pdf'), target: '_blank'

  = paginate wages, :theme => 'twitter-bootstrap-3'

app/views/wages/_spec.pdf.haml
- organization = wage.organization.decorate
- total = wage.salary + wage.payroll_tax
- wage = wage.decorate
- sum = 0
%table
  %tr
    %td
      .pull-left
        %h2= wage.wage_period.name
    %td
    %td
      - if organization.logo?
        .pull-right.logo
          %h1= image_tag(organization.logo_path)
      - else
        .pull-right
          %h1= organization.name
  %tr
    %td
      %h2= wage.employee.full_name
  %tr
    %td
      = t(:salary)
    %td.pull-right
      = number_with_precision(wage.salary, precision: 2)
    %td.filler
  %tr
    %td
      = t(:tax)
    %td.pull-right
      = wage.wage_tax
    %td
      .pull-right
        = wage.employee.tax_table.name
        = " : "
        = wage.employee.tax_table_column
  %tr
    %td
      = t(:net)
    %td.pull-right
      = number_with_precision(wage.amount, precision: 2)
    %td.filler
  %tr
    %td
      = t(:payroll_tax)
    %td.pull-right
      = wage.wage_payroll_tax
    %td.filler
  %tr
    %td
      = "#{t(:total)} ( #{t(:salary)} + #{t(:payroll_tax)} )"
    %td.pull-right
      = number_with_precision(total, precision: 2)
    %td.filler
  %tr
    %td.filler
  %tr
    %td{colspan: '2'}
      %h2= t(:based_on)
  %tr
    %th
      .pull-left
        = t(:account_date)
    %th
      .pull-left
        = t(:description)
    %th
      .pull-right.numeric
        = t(:amount)
  - verificate_items.each do | item |
    %tr
      %td
        .pull-left
          = item.posting_date
      %td
        .pull-left
          = item.verificate_description
      %td
        .pull-right.numeric
          - amount = item.credit - item.debit
          - sum = sum + amount
          = number_with_precision(amount, precision: 2)
  %tr
    %td
      .pull-left
    %td
      .pull-left
        = t(:total)
    %td
      .pull-right.numeric
        = number_with_precision(sum, precision: 2)

app/views/wages/index.html.haml
- if @wage_period.can_report_wage?
  = link_to "#{t(:create)} #{t(:wage)}", new_wage_period_wage_path(@wage_period), class: 'btn btn-success'
  = link_to "#{t(:create)} #{t(:verificate)}", state_change_wage_period_path(@wage_period, event: 'mark_wage_reported'), method: 'post', class: 'btn btn-success'

.table-responsive
  %table{:class => 'table table-striped'}
    %thead
      %tr
        %th= t(:name)
        %th= t(:from)
        %th= t(:to)
        %th= t(:payment_date)
        %th.numeric= t(:tax)
        %th.numeric= t(:amount)
        %th
        %th
        %th
    %tbody
      - @wages.each do |wage|
        %tr
          %td= wage.employee.name
          %td= wage.wage_from
          %td= wage.wage_to
          %td= wage.payment_date
          %td.numeric= wage.tax
          %td.numeric= wage.amount
          %td
            - if wage.has_document?
              = link_to doc_icon, wage_period_wage_path(@wage_period, wage, format: 'pdf'), target: '_blank'
          %td.numeric= link_to settings_icon, edit_wage_period_wage_path(@wage_period, wage)
          %td.numeric= delete_modal wage, wage_period_wage_path(@wage_period, wage), '#mdId'

  = paginate @wages, :theme => 'twitter-bootstrap-3'

= render partial: 'shared/modal_deletes', locals: {modalId: 'mdId'}

app/views/wages/show.pdf.haml
= render partial: 'spec', locals: {wage: wage, verificate_items: verificate_items}