config/routes.rb
require 'resque/server'
Emmy::Application.routes.draw do
  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'

  mount Resque::Server.new, at: "/resque"

  root 'pages#start'
  devise_for :users, controllers: {sessions: 'user_sessions'}
  [:about, :start, :formats, :test].each do |p|
    get "/#{p}", to: "pages##{p}"
  end

  namespace :admin do
    resources :organizations
    resources :users do
      member do
        patch 'update_roles', as: :update_roles
      end
    end
    get 'dashboard', to: 'dashboard#index'
    constraints lambda { |request| request.env['warden'].authenticate? && request.env['warden'].user.superadmin? } do
      mount Resque::Server.new, at: "resque"
    end
  end

  get "organization_selector", to: "dashboard#organization_selector"
  get ':organization_slug', to: 'organizations#show', as: 'organization'
  patch ':organization_slug', to: 'organizations#update'
  scope ':organization_slug' do
    get "dashboard", to: "dashboard#index"

    resources :accounting_periods

    resources :accounting_plans do
      post 'disable_accounts', as: :disable_accounts
      resources :accounting_groups
      resources :accounting_classes
      resources :accounts do
        post 'toggle_active', as: :toggle_active
      end
    end
    get 'accounts_receivables', to: 'accounts_receivables#index', as: 'accounts_receivables'
    get 'accounts_payables', to: 'accounts_payables#index', as: 'accounts_payables'
    resources :batches
    resources :closing_balances do
      resources :closing_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :comments
    resources :contact_relations
    resources :contacts
    resources :conversions do
      delete 'clear'
    end
    resources :customers do
      collection do
        get 'name_search', as: :name_search
        get 'city_search', as: :city_search
      end
    end
    resources :default_codes
    resources :default_code_headers
    resources :documents
    resources :employees
    resources :export_bank_files
    resources :economics_wizard do
      collection do
        get 'start'
        get 'stop'
      end
    end
    resources :export_bank_file_rows
    get 'helps/show_help'
    get 'helps/show_chapter_help'
    get 'helps/show_message'
    resources :import_bank_files do
      resources :import_bank_file_rows do
        get 'match_verificate', as: :match_verificate
        get 'set_verificate', as: :set_verificate
        get 'set_template_verificate', as: :set_template_verificate
      end
    end
    resources :import_batches, only: [:new, :create]
    resources :imports do
      resources :import_batches, only: [:new, :create]
      member do
        post 'state_change', as: :state_change
        get 'new_purchase', as: :new_purchase
        post 'create_purchase', as: :create_pruchase
      end
    end
    resources :ink_code_headers
    resources :ink_codes
    resources :inventories do
      resources :inventory_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :items
    resources :ledgers do
      resources :ledger_accounts
    end
    resources :ledger_transactions
    resources :manuals
    resources :mail_templates
    resources :materials
    resources :ne_code_headers
    resources :ne_codes
    resources :opening_balances do
      post 'create_from_ub'
      resources :opening_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :production_batches, only: [:new, :create]
    resources :productions do
      resources :production_batches, only: [:new, :create]
      resources :materials
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :purchases do
      resources :purchase_items
      member do
        post 'state_change', as: :state_change
      end
      post 'single_purchase', as: :single_purchase
    end

    get 'reports/order_verificates_report'
    get 'reports/order_ledger_report'
    get 'reports/order_result_report'
    get 'reports/order_balance_report'
    get 'reports/sale_statistics'
    post 'reports/verificates'
    post 'reports/ledger'
    post 'reports/result_report'
    post 'reports/balance_report'

    resources :result_units

    resources :reversed_vats do
      resources :reversed_vat_reports
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :sales do
      resources :sale_items
      member do
        post 'state_change', as: :state_change
        post 'send_email', as: :send_email
        post 'send_reminder_email', as: :send_reminder_email
        post 'regenerate_invoice', as: :regenerate_invoice
      end
      collection do
        get 'invoice_search', as: :invoice_search
      end
    end
    get 'statistics/index'
    resources :shelves

    resources :sie_exports
    resources :sie_imports

    resources :simplified_sales

    resources :suppliers

    resources :stock_values do
      resources :stock_value_items
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :tax_code_headers
    resources :tax_codes

    resources :tax_returns do
      resources :tax_return_reports
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :tax_tables do
      resources :tax_table_rows
    end

    post 'templates_import', to: 'templates#import', as: 'templates_import'
    resources :templates do
      resources :template_items
    end

    resources :transfers do
      member do
        post 'send_package', as: :send_package
        post 'receive_package', as: :receive_package
      end
    end
    resources :units
    resources :users do
      member do
        patch :update_roles, as: :update_roles
      end
    end
    resources :vat_periods do
      resources :vat_reports
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :vats
    resources :verificates do
      resources :verificate_items
      member do
        post 'state_change', as: :state_change
        post 'reversal', as: :reversal
        post 'add_verificate_items', as: :add_verificate_items
      end
    end
    resources :wage_periods do
      resources :wages
      resources :wage_reports
      member do
        post 'state_change', as: :state_change
        post 'create_wage', as: :create_wage
      end
    end
    resources :wages_wizard do
      collection do
        get 'start'
        get 'stop'
      end
    end
    resources :warehouses
  end

end

app/controllers/sales_controller.rb
# @TODO check state on update/destroy before doing anything.
class SalesController < ApplicationController
  load_and_authorize_resource through: :current_organization

  before_action :new_breadcrumbs, only: [:new, :create]
  before_action :show_breadcrumbs, only: [:show, :update]
  before_action :add_warehouses, only: [:index, :new, :invoice_search]
  before_action :add_search_filter, only: [:index]

  def create
    @sale = Sale.new sale_params
    @sale.user = current_user
    @sale.organization = current_organization
    if @sale.save
      redirect_to sale_path(@sale), notice: "#{t(:sale)} #{t(:was_successfully_created)}"
    else
      flash.now[:danger] = "#{t(:failed_to_create)} #{t(:sale)}"
      @warehouses = current_organization.warehouses
      @customers = current_organization.customers
      gon.push customers: ActiveModel::Serializer::CollectionSerializer.new(@customers, each_serializer: CustomerSerializer)
      render action: :new
    end
  end

  def index
    @breadcrumbs = [[t(:sales)]]
    @sales = @sales.order 'approved_at desc'
    @sales = @sales.page(params[:page]).decorate
    @mail_templates_invoice = current_organization.mail_templates.invoice
    @mail_templates_reminder = current_organization.mail_templates.reminder
    respond_to do |format|
      format.csv
      format.pdf do
        render(pdf: 'invoices', template: 'sales/index.pdf.haml', layout: 'pdf')
      end
      format.html
    end
  end

  def new
    @warehouses = current_organization.warehouses
    @sale.customer_id = params[:customer_id] if params[:customer_id]
    @mail_templates_invoice = current_organization.mail_templates.invoice
    @mail_templates_reminder = current_organization.mail_templates.reminder
    @customers = current_organization.customers
    gon.push customers: ActiveModel::Serializer::CollectionSerializer.new(@customers, each_serializer: CustomerSerializer)
  end

  def show
    @non_decorated_sale = @sale
    @sale = @sale.decorate
    @mail_templates_invoice = current_organization.mail_templates.invoice
    @mail_templates_reminder = current_organization.mail_templates.reminder
    respond_to do |format|
      format.html { @warehouses = current_organization.warehouses }
      format.pdf do
        if params.has_key?('regenerate')
          render(pdf: "invoice_#{@sale.invoice_number}",
                 template: 'sales/show.pdf.haml',
                 layout: 'pdf')
        elsif @sale.document.nil?
          fail ArgumentError
        else
          send_file(@sale.document.upload.path,
                    filename: "invoice_#{@sale.invoice_number}.pdf",
                    type: 'application/pdf')
        end
      end
    end
  end

  def update
    if @sale.update_attributes(sale_params)
      redirect_to sale_path(@sale), notice: "#{t(:sale)} #{t(:was_successfully_updated)}"
    else
      flash.now[:danger] = "#{t(:failed_to_update)} #{t(:sale)}"
      @warehouses = current_organization.warehouses
      render action: :show
    end
  end

  def destroy
    if @sale.can_delete?
      @sale.destroy
      redirect_to sales_path, notice: "#{t(:sale)} #{t(:was_successfully_deleted)}"
    else
      redirect_to sales_path, alert: "#{t(:sale)} #{t('errors.messages.can_not_be_deleted')}"
    end
  end

  def state_change
    @sale = current_organization.sales.find(params[:id])
    deliver = params[:sale].nil? ? nil : params[:sale][:report_delivery]
    authorize! :manage, @sale
    if @sale.state_change(params[:event], params[:state_change_at], deliver)
      msg_h = { notice: t(:success) }
    else
      msg_h = { alert: t(:fail) }
    end
    redirect_to @sale, msg_h
  end

  def send_email
    @sale = current_organization.sales.find(params[:id])
    if params[:sale].present?
      @mail_template = current_organization.mail_templates.find(params[:sale][:mail_template])
    end
    authorize! :manage, @sale
    if @sale.send_invoice!(@mail_template)
      flash[:notice] = t(:sent_email)
    else
      flash[:danger] = "#{t(:unable_to_send_email)}: #{@sale.errors[:custom_error].join(',')}"
    end
    redirect_to sales_path
  end

  def send_reminder_email
    @sale = current_organization.sales.find(params[:id])
    if params[:sale].present?
      @mail_template = current_organization.mail_templates.find(params[:sale][:mail_template])
    end
    authorize! :manage, @sale
    if @sale.send_reminder!(@mail_template)
      flash[:notice] = t(:sent_email)
    else
      flash[:danger] = "#{t(:unable_to_send_email)}: #{@sale.errors[:custom_error].join(',')}"
    end
    redirect_to sales_path
  end

  def regenerate_invoice
    @sale.document.destroy if @sale.document
    @sale.generate_invoice
    redirect_to @sale
  end

  private

  def sale_params
    params.require(:sale).permit(:warehouse_id, :customer_id, :contact_email, :contact_name,
                                 :contact_telephone, :payment_term, :invoice_text)
  end

  def new_breadcrumbs
    @breadcrumbs = [[t(:sales), sales_path], ["#{t(:new)} #{t(:sale)}"]]
  end

  def show_breadcrumbs
    @breadcrumbs = [[t(:sales), sales_path], ["##{@sale.invoice_number}"]]
  end

  def state_param
    p = params.permit([:state, :locale, 'organization-slug'])
    if p[:state] && Sale::FILTER_STAGES.include?(p[:state].to_sym)
      p[:state]
    else
      nil
    end
  end

  def add_warehouses
    @warehouses = current_organization.warehouses
  end

  def add_search_filter
    search_params.each do |key, value|
      @sales = @sales.where(key => value) if value
    end

    if search_params[:invoice_number] && @sales.size == 1
      redirect_to sale_path(@sales.first)
    end

    add_date_constraint(:newer_than) unless params[:newer_than].blank?
    add_date_constraint(:older_than) unless params[:older_than].blank?

    # Uses a named scope.
    @sales = @sales.send(state_param.to_sym) if state_param
  end

  # Create a hash with all the keys, set value to nil unless exist in params.
  def search_params
    unless @search_params
      @search_params = {}.with_indifferent_access
      [:warehouse_id, :user_id, :invoice_number].map do |key|
        @search_params[key] = (!params[key].blank?) ? params[key].to_s : nil
      end
    end
    @search_params
  end

  def add_date_constraint(direction)
    d = (direction.eql? :newer_than) ? '>' : '<'
    @sales = @sales.where("approved_at #{d} ?", date_param(direction))
  end

  # Only allow numers and - as date params.
  # Return the passed year/month the first in that month.
  def date_param(direction)
    return "#{params[direction]}-01" if params[direction].match(/^[0-9]{4}-[0-9]{2}$/)
    fail ArgumentError
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_action_buttons.html.haml
- date_now = DateTime.now.strftime("%Y-%m-%d")
.form-button-group
  .actions
    - if @sale.can_edit_items?
      = link_to t(:add_batch), new_sale_sale_item_path(@sale), class: 'btn btn-primary pull-left'

    - # Don't show next-step unless there are items in the sale.
    - if @sale.sale_items.count > 0 && !@sale.completed?

      - if @sale.can_edit_items?
        %button{:class=>'btn btn-primary', :type=>'button', :'data-toggle' => 'modal', :'data-target' => '#scId'}
          = t(:ordered)
        = render partial: 'shared/modal_state_changes', locals: {modalId: 'scId',
                                                       date_label: t(:the_date),
                                                       date_field: :state_change_at,
                                                       date_value: date_now,
                                                       min_date: nil,
                                                       max_date: nil,
                                                       checkbox: :report_delivery,
                                                       model: @sale,
                                                       form_path: state_change_sale_path(@sale),
                                                       event: 'mark_prepared',
                                                       return_path: sale_path(@sale)}

      - elsif !@sale.canceled?
        - if !@sale.delivered?
          %button{:class=>'btn btn-primary', :type=>'button', :'data-toggle' => 'modal', :'data-target' => '#scdId'}
            = t(:delivered)
          = render partial: 'shared/modal_state_changes', locals: {modalId: 'scdId',
                                                       date_label: t(:the_date),
                                                       date_field: :state_change_at,
                                                       date_value: date_now,
                                                       min_date: nil,
                                                       max_date: nil,
                                                       model: @sale,
                                                       form_path: state_change_sale_path(@sale),
                                                       event: 'deliver',
                                                       return_path: sale_path(@sale)}

        - if !@sale.paid?
          %button{:class=>'btn btn-primary', :type=>'button', :'data-toggle' => 'modal', :'data-target' => '#scpId'}
            = t(:paid)
          = render partial: 'shared/modal_state_changes', locals: {modalId: 'scpId',
                                                       date_label: t(:the_date),
                                                       date_field: :state_change_at,
                                                       date_value: date_now,
                                                       min_date: nil,
                                                       max_date: nil,
                                                       model: @sale,
                                                       form_path: state_change_sale_path(@sale),
                                                       event: 'pay',
                                                       return_path: sale_path(@sale)}


          - if !@sale.invoice_sent? && !@sale.overdue?
            - title = t(:send_email_to_customer)
            %button{:class=>'btn btn-primary', :type=>'button', :'data-toggle' => 'modal', :'data-target' => '#diId'}
              = t(:send_email_with_invoice)
            = render partial: 'shared/modal_dialogs', locals: {modalId: 'diId',
                                                       title: title,
                                                       model: @sale,
                                                       select: 'mail_template',
                                                       form_path: send_email_sale_path(@sale),
                                                       return_path: sales_path,
                                                       collection: @mail_templates_invoice}

          - if @sale.overdue?
            - title = t(:send_reminder_to_customer)
            %button{:class=>'btn btn-primary', :type=>'button', :'data-toggle' => 'modal', :'data-target' => '#drId'}
              = t(:send_reminder_to_customer)
            = render partial: 'shared/modal_dialogs', locals: {modalId: 'drId',
                                                       title: title,
                                                       model: @sale,
                                                       select: 'mail_template',
                                                       form_path: send_reminder_email_sale_path(@sale),
                                                       return_path: sales_path,
                                                       collection: @mail_templates_reminder}

          %button{:class=>'btn btn-primary', :type=>'button', :'data-toggle' => 'modal', :'data-target' => '#sccId'}
            = t(:cancel)
          = render partial: 'shared/modal_state_changes', locals: {modalId: 'sccId',
                                                       date_label: t(:the_date),
                                                       date_field: :state_change_at,
                                                       date_value: date_now,
                                                       min_date: nil,
                                                       max_date: nil,
                                                       model: @sale,
                                                       form_path: state_change_sale_path(@sale),
                                                       event: 'mark_canceled',
                                                       return_path: sale_path(@sale)}

app/views/sales/_datepicker.html.haml
%div{:class=>"form-group"}
  %label{:class => "labels_width control-label"}
    =txt
  %input{:type => "hidden", :id => id, :name=> name, :value =>value}
  %div{:class=>"col-sm-11"}
    %div{:class => "input-group"}
      %input{:type => "text", :class => "form-control", :datepicker_popup=>"yyyy-MM-dd", :ng_model=>model, :is_open=>isOpen, :datepicker_options=>dpOptions, :show_button_bar=>"false", :readonly =>"true"}
        %span{:class => "input-group-btn"}
          %button{:class => "btn btn-default", :ng_click=>onclick }
            %i{ :class => "glyphicon glyphicon-calendar"}

app/views/sales/_list.html.haml
%table{:class => 'table table-striped'}
  %thead
    %tr
      %th= t(:invoice_number)
      %th= t(:approved_at)
      %th= t(:warehouse)
      %th= t(:customer)
      %th= t(:state)
      %th
      %th
      %th
  %tbody
    - sales.each do |sale|
      %tr
        %td= sale.invoice_number
        %td= sale.approved_at
        %td= link_to sale.warehouse_name, sale.warehouse
        %td= link_to sale.customer_name, sale.customer
        %td
          - sale.states.each do |s|
            = s
        - if sale.prepared?
          - show =  link_to doc_icon, sale_path(sale, format: :pdf), :target => "_blank"
        - else
          - show = ' '
        %td= show
        %td= link_to settings_icon, sale
        %td= delete_modal sale, nil, '#mdsId'

= paginate sales, :theme => 'twitter-bootstrap-3'

= render partial: 'shared/modal_deletes', locals: {modalId: 'mdsId'}

app/views/sales/_select_customer.html.haml
%div{:class => ((f.error :customer_id) ? "form-group select required sale_customer has-error": "form-group select required sale_customer")}
  = f.label :customer, class: 'string optional labels_width control-label', for: 'customer_ref', required: true
  = f.input :customer_id, as: :hidden
  %div{:class=>"fields_width"}
    %input{:id => 'customer_ref', :autocomplete=>'off',  :class=>"typeahead form-control"}
    = f.error :customer_id
  .form-suffix-text
    = link_to "#{t(:create)} #{t(:customer)}", new_customer_path(return_path: new_sale_path)

= f.input :contact_name, :autocomplete=>'off', :class=>'typeahead'
= f.input :contact_email, disabled: !@sale.new_record?
= f.input :contact_telephone, disabled: !@sale.new_record?

:javascript

  $(document).ready(function() {

    var data = gon.customers;
    var contacts = [];
    set_customer_ref();

    $('#customer_ref').typeahead({
      highlight: true}, {
      name: 'customer',
      source: function (query, process) {
        var customers = [];
        $.each(data, function (i, customer) {
          if (customer.name.toLowerCase().indexOf(query.trim().toLowerCase()) != -1) {
            //map[contact.email] = contact;
            customers.push({value: customer.name});
          }
        });
        process(customers);
      }
    });

    $('#customer_ref').bind('typeahead:selected', function(event, obj, name) {
      var name = obj['value'];

      $('#sale_customer_id').val('');
      $('#sale_payment_term').val('0');
      for (var i = 0; i < data.length; i++) {

        if (data[i].name  == name) {
        //$scope.reference = $scope.customer[i].contacts;
          contacts = data[i].contacts;
          $('#sale_customer_id').val(data[i].id);
          $('#sale_payment_term').val(data[i].payment_term);
          set_contact(data[i]);

        }
      }
     });

    function set_customer_ref() {
      for (var i = 0; i < data.length; i++) {
        if (data[i].id  == $('#sale_customer_id').val()) {
          $('#customer_ref').val(data[i].name);
        }
      }
    }
    function set_contact(customer) {
      var contact_info = {
        name: "",
        email: customer.email,
        telephone: customer.telephone
      }

      var contact = customer.contacts[0]
      var primary_id = customer.primary_contact_id;
      if (primary_id) {
        for (var x = 0; x < customer.contacts.length; x++) {
          if (primary_id == customer.contacts[x].id) {
            contact = customer.contacts[x];
          }
        }
      }
      if (contact) {
        if (contact.email && contact.email != "") {
          contact_info.email = contact.email
        }
        if (contact.telephone && contact.telephone != "") {
          contact_info.telephone = contact.telephone
        }
        contact_info.name = contact.name
      }

      $('#sale_contact_name').val(contact_info.name);
      $('#sale_contact_email').val(contact_info.email);
      $('#sale_contact_telephone').val(contact_info.telephone);
    }

    $('#sale_contact_name').typeahead({
      highlight: true}, {
      name: 'contact',
      source: function (query, process) {
        var ccontacts = [];
        $.each(contacts, function (i, contact) {
          if (contact.name.toLowerCase().indexOf(query.trim().toLowerCase()) != -1) {
            //map[contact.email] = contact;
            ccontacts.push({value: contact.name});
          }
        });
        process(ccontacts);
      }
    });

    $('#sale_contact_name').bind('typeahead:selected', function(event, obj, name) {
      var name = obj['value'];
      $('#sale_contact_email').val('');
      $('#sale_contact_telephone').val('');
      for (var i = 0; i < contacts.length; i++) {
        if (contacts[i].name  == name) {
          $('#sale_contact_email').val(contacts[i].email);
          $('#sale_contact_telephone').val(contacts[i].telephone);
        }
      }
     });

  })

app/views/sales/index.html.haml
.row
  .col-sm-8.col-md-5.pull-left
    = link_to "#{t(:create)} #{t(:sale)}", new_sale_path, class: 'btn btn-success'
  .col-sm-40.col-md-40.pull-right.text-right
    = form_tag sales_path, class: 'form-inline submit-on-change', method: :get, enforce_utf8: false do
      = text_field_tag('locale' , params[:locale], type:'hidden')

      = select_tag(:newer_than,
        options_for_select(months_list, params[:newer_than]),
        class: 'btn btn-default',
        prompt: "#{t(:filter)} #{t(:newer_than)}: #{t(:all)}")

      = select_tag(:older_than,
        options_for_select(months_list, params[:older_than]),
        class: 'btn btn-default',
        prompt: "#{t(:filter)} #{t(:older_than)}: #{t(:all)}")

      = select_tag(:state,
        options_for_select(Sale::FILTER_STAGES.each.collect{|s| [t(s), s]}, params[:state]),
        class: 'btn btn-default',
        prompt: "#{t(:filter)} #{t(:state)}: #{t(:all)}")

      = select_tag(:warehouse_id,
        options_for_select(@warehouses.each.collect{|w| [w.name, w.id]}, params[:warehouse_id]),
        class: 'btn btn-default',
        prompt: "#{t(:filter)} #{t(:warehouses)}: #{t(:all)}")

      = select_tag(:user_id,
        options_for_select(current_organization.users.each.collect{|u| [u.name, u.id]}, params[:user_id]),
        class: 'btn btn-default',
        prompt: "#{t(:filter)} #{t(:users)}: #{t(:all)}")

      .input-group
        = text_field_tag('invoice_number',
          params[:invoice_number],
          placeholder: t(:invoice_search),
          class: 'form-control')
        .span.input-group-btn
          = button_tag(search_icon, class: 'btn btn-default')
  .clear &nbsp;

.table-responsive
  %table{:class => 'table table-striped'}
    %thead
      %tr
        %th= t(:invoice_number)
        %th= t(:approved_at)
        %th= t(:warehouse)
        %th= t(:customer)
        %th= t(:our_reference)
        %th= t(:state)
        %th
        %th
        %th
    %tbody
      - @sales.each do |sale|
        %tr
          %td= sale.invoice_number
          %td= sale.approved_at
          %td= link_to sale.warehouse_name, sale.warehouse
          %td= link_to sale.customer_name, sale.customer
          %td= sale.user
          %td
            - sale.states.each do |s|
              = s
          %td
            - if sale.has_document?
              = link_to doc_icon, sale_path(sale, format: 'pdf'), target: '_blank'
            - if sale.prepared? && !sale.invoice_sent? && !sale.overdue?
              - dc = 'dialogContent' + sale.invoice_number.to_s
              - title = t(:send_email_to_customer)
              %button{:class=>'btn btn-xs', :type=>'button', :'data-toggle' => 'modal', :'data-target' => '#id_'+dc}
                = envelope_icon
              = render partial: 'shared/modal_dialogs', locals: {modalId: 'id_'+dc,
                                                       title: title,
                                                       model: sale,
                                                       select: 'mail_template',
                                                       form_path: send_email_sale_path(sale),
                                                       return_path: sales_path,
                                                       collection: @mail_templates_invoice}

            - if sale.overdue?
              - dc = 'dialogContent' + sale.invoice_number.to_s
              - title = t(:send_reminder_to_customer)
              %button{:class=>'btn btn-xs btn-warning', :type=>'button', :'data-toggle' => 'modal', :'data-target' => '#id_'+dc}
                = envelope_icon
              = render partial: 'shared/modal_dialogs', locals: {modalId: 'id_'+dc,
                                                       title: title,
                                                       model: sale,
                                                       select: 'mail_template',
                                                       form_path: send_reminder_email_sale_path(sale),
                                                       return_path: sales_path,
                                                       collection: @mail_templates_reminder}

          %td= link_to settings_icon, sale
          %td= delete_modal sale, nil, '#mdId'

  = paginate @sales, :theme => 'twitter-bootstrap-3'
  .row
    .col-md-48
      = link_to "csv", url_for(params: params.permit(:locale, :organization_slug).merge(format: 'csv')), class: 'btn btn-default'
      = link_to "pdf", url_for(params: params.permit(:locale, :organization_slug).merge(format: 'pdf')), class: 'btn btn-default'
  %br

= render partial: 'shared/modal_deletes', locals: {modalId: 'mdId'}

:javascript
  $(document).ready(function() {
    var path = document.location.pathname + document.location.search
    $('#selp').val(path);
  });

app/views/sales/index.pdf.haml
- @sales.each do |sale|
  = render partial: 'invoice', locals: {sale: sale}

app/views/sales/new.html.haml
- url = "#{request.path_info.split('/')[1]}"+'/'
= render 'form'

app/views/sales/show.html.haml
%ul{:class => 'nav nav-tabs'}
  %li.active= link_to t(:base_information), "#sale-form", {"data-toggle" => "tab"}
  %li= link_to t(:comments), "#comment-index", {"data-toggle" => "tab"}

.tab-content
  #sale-form.tab-pane.active
    .search-by-invoice-number
      = form_tag sales_path, class: 'form-inline submit-on-change', method: :get do
        .input-group
          = text_field_tag('invoice_number',
            params[:invoice_number],
            placeholder: t(:invoice_search),
            class: 'form-control')
          .span.input-group-btn
            = button_tag(search_icon, class: 'btn btn-default')
    %br
    = render partial: 'form'

    .form-horizontal
      .form-group
        .labels_width.control-label
          %label= t(:form_items)
        .fields_width
          = render partial: 'sale_items/list', locals: {sale_items: @sale.sale_items}

      - if @sale.has_document?
        .labels_width.control-label
          %label= "PDF #{t(:invoice)}"
        .fields_width.form-control-static
          = link_to doc_icon, sale_path(@sale, format: 'pdf'), target: '_blank'
          = link_to refresh_icon, regenerate_invoice_sale_path(@sale), method: :post

    - if @sale.can_edit_items? or @sale.sale_items.count > 0 && !@sale.completed? && !@sale.canceled?
      = render partial: 'action_buttons'

  #comment-index.tab-pane
    = render partial: 'comments/index', locals: {comments: @non_decorated_sale.comments, parent: @non_decorated_sale}

:javascript
  $(document).ready(function() {

  $('a[data-toggle="tab"]').on("click", function(e) {
   localStorage.setItem('sale_tab', $(e.target).attr("href").substr(1));
  });

  var lastTab = localStorage.getItem('sale_tab');
  if (lastTab) {
    $('ul.nav-tabs').children().removeClass('active');
    $('a[href="#'+ lastTab +'"]').parents('li:first').addClass('active');
    $('div.tab-content').children().removeClass('active');
    $('#'+lastTab).addClass('active');
  }
  });