config/routes.rb
require 'resque/server'
Emmy::Application.routes.draw do
  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'

  mount Resque::Server.new, at: "/resque"

  root 'pages#start'
  devise_for :users, controllers: {sessions: 'user_sessions'}
  [:about, :start, :formats, :test].each do |p|
    get "/#{p}", to: "pages##{p}"
  end

  namespace :admin do
    resources :organizations
    resources :users do
      member do
        patch 'update_roles', as: :update_roles
      end
    end
    get 'dashboard', to: 'dashboard#index'
    constraints lambda { |request| request.env['warden'].authenticate? && request.env['warden'].user.superadmin? } do
      mount Resque::Server.new, at: "resque"
    end
  end

  get "organization_selector", to: "dashboard#organization_selector"
  get ':organization_slug', to: 'organizations#show', as: 'organization'
  patch ':organization_slug', to: 'organizations#update'
  scope ':organization_slug' do
    get "dashboard", to: "dashboard#index"

    resources :accounting_periods

    resources :accounting_plans do
      post 'disable_accounts', as: :disable_accounts
      resources :accounting_groups
      resources :accounting_classes
      resources :accounts do
        post 'toggle_active', as: :toggle_active
      end
    end
    get 'accounts_receivables', to: 'accounts_receivables#index', as: 'accounts_receivables'
    get 'accounts_payables', to: 'accounts_payables#index', as: 'accounts_payables'
    resources :batches
    resources :closing_balances do
      resources :closing_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :comments
    resources :contact_relations
    resources :contacts
    resources :conversions do
      delete 'clear'
    end
    resources :customers do
      collection do
        get 'name_search', as: :name_search
        get 'city_search', as: :city_search
      end
    end
    resources :default_codes
    resources :default_code_headers
    resources :documents
    resources :employees
    resources :export_bank_files
    resources :economics_wizard do
      collection do
        get 'start'
        get 'stop'
      end
    end
    resources :export_bank_file_rows
    get 'helps/show_help'
    get 'helps/show_chapter_help'
    get 'helps/show_message'
    resources :import_bank_files do
      resources :import_bank_file_rows do
        get 'match_verificate', as: :match_verificate
        get 'set_verificate', as: :set_verificate
        get 'set_template_verificate', as: :set_template_verificate
      end
    end
    resources :import_batches, only: [:new, :create]
    resources :imports do
      resources :import_batches, only: [:new, :create]
      member do
        post 'state_change', as: :state_change
        get 'new_purchase', as: :new_purchase
        post 'create_purchase', as: :create_pruchase
      end
    end
    resources :ink_code_headers
    resources :ink_codes
    resources :inventories do
      resources :inventory_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :items
    resources :ledgers do
      resources :ledger_accounts
    end
    resources :ledger_transactions
    resources :manuals
    resources :mail_templates
    resources :materials
    resources :ne_code_headers
    resources :ne_codes
    resources :opening_balances do
      post 'create_from_ub'
      resources :opening_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :production_batches, only: [:new, :create]
    resources :productions do
      resources :production_batches, only: [:new, :create]
      resources :materials
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :purchases do
      resources :purchase_items
      member do
        post 'state_change', as: :state_change
      end
      post 'single_purchase', as: :single_purchase
    end

    get 'reports/order_verificates_report'
    get 'reports/order_ledger_report'
    get 'reports/order_result_report'
    get 'reports/order_balance_report'
    get 'reports/sale_statistics'
    post 'reports/verificates'
    post 'reports/ledger'
    post 'reports/result_report'
    post 'reports/balance_report'

    resources :result_units

    resources :reversed_vats do
      resources :reversed_vat_reports
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :sales do
      resources :sale_items
      member do
        post 'state_change', as: :state_change
        post 'send_email', as: :send_email
        post 'send_reminder_email', as: :send_reminder_email
        post 'regenerate_invoice', as: :regenerate_invoice
      end
      collection do
        get 'invoice_search', as: :invoice_search
      end
    end
    get 'statistics/index'
    resources :shelves

    resources :sie_exports
    resources :sie_imports

    resources :simplified_sales

    resources :suppliers

    resources :stock_values do
      resources :stock_value_items
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :tax_code_headers
    resources :tax_codes

    resources :tax_returns do
      resources :tax_return_reports
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :tax_tables do
      resources :tax_table_rows
    end

    post 'templates_import', to: 'templates#import', as: 'templates_import'
    resources :templates do
      resources :template_items
    end

    resources :transfers do
      member do
        post 'send_package', as: :send_package
        post 'receive_package', as: :receive_package
      end
    end
    resources :units
    resources :users do
      member do
        patch :update_roles, as: :update_roles
      end
    end
    resources :vat_periods do
      resources :vat_reports
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :vats
    resources :verificates do
      resources :verificate_items
      member do
        post 'state_change', as: :state_change
        post 'reversal', as: :reversal
        post 'add_verificate_items', as: :add_verificate_items
      end
    end
    resources :wage_periods do
      resources :wages
      resources :wage_reports
      member do
        post 'state_change', as: :state_change
        post 'create_wage', as: :create_wage
      end
    end
    resources :wages_wizard do
      collection do
        get 'start'
        get 'stop'
      end
    end
    resources :warehouses
  end

end

app/models/reversed_vat.rb
class ReversedVat < ActiveRecord::Base

  # t.string   :name
  # t.datetime :vat_from
  # t.datetime :vat_to
  # t.string   :state
  # t.datetime :calculated_at
  # t.datetime :reported_at
  # t.datetime :deadline
  # t.integer  :organization_id
  # t.integer  :accounting_period_id

  # t.timestamps

  #attr_accessible :name, :vat_from, :vat_to, :accounting_period_id, :deadline

  belongs_to :organization
  belongs_to :accounting_period
  has_many   :reversed_vat_reports, dependent: :destroy

  validates :accounting_period, presence: true
  validates :name, presence: true, uniqueness: {scope: :organization_id}
  validates :vat_from, presence: true
  validates :vat_to, presence: true
  validate :check_to
  validate :overlaping_period
  validates :deadline, presence: true
  VALID_JOBS = %w(reversed_vat_report_job)

  def check_to
    if vat_from >= vat_to
      errors.add(:vat_to, I18n.t(:period_error))
    end
  end

  def overlaping_period
    p = ReversedVat
            .where('organization_id = ? and vat_to >= ? and vat_from <= ?' ,
                   organization_id, vat_from, vat_to).count
    if new_record?
      errors.add(:vat_to, I18n.t(:within_period)) if p > 0
    else
      errors.add(:vat_to, I18n.t(:within_period)) if p > 1
    end
  end

  STATE_CHANGES = [:mark_calculated, :mark_reported, :finnish_calculation]

  def state_change(event, changed_at = nil, user_id = nil)
    return false unless STATE_CHANGES.include?(event.to_sym)
    send(event, changed_at, user_id)
  end

  state_machine :state, initial: :preliminary do
    before_transition on: :mark_calculated, do: :calculate
    after_transition on: :mark_calculated, do: :enqueue_reversed_vat_report
    before_transition on: :mark_reported, do: :report

    event :mark_calculated do
      transition [:preliminary, :calculated] => :start_calculation
    end
    event :finnish_calculation do
      transition start_calculation: :calculated
    end
    event :mark_reported do
      transition calculated: :reported
    end
  end

  def calculate(transition)
    self.calculated_at = transition.args[0]
  end

  def report(transition)
    self.reported_at = transition.args[0]
  end

  def enqueue_reversed_vat_report
    logger.info '** ReversedVat enqueue a job that will create report.'
    ReversedVatJob.perform_later(id, 'reversed_vat_report_job')
  end

  # Run from the 'ReversedVatJob' model
  def reversed_vat_report_job
    logger.info '** ReversedVat reversed_vat_report_job start'
    reversed_vat_report_creator = Services::ReversedVatReportCreator.new(self)
    reversed_vat_report_creator.delete_reversed_vat_report
    if reversed_vat_report_creator.report
      logger.info "** ReversedVat #{id} reversed_vat_report returned ok, marking complete"
      finnish_calculation
    else
      logger.info "** ReversedVat #{id} reversed_vat_report did NOT return ok, not marking complete"
    end
  end

  def can_calculate?
    return false if state == 'reported'
    true
  end

  def can_report?
    return true if state == 'calculated'
    false
  end

  def calculated?
    ['calculated', 'reported'].include? state
  end

  def reported?
    return true if state == 'reported'
    false
  end

  def can_delete?
    return false if reported?
    return false if accounting_period.active
    true
  end
end

app/controllers/reversed_vats_controller.rb
class ReversedVatsController < ApplicationController
  respond_to :html, :json
  load_and_authorize_resource through: :current_organization

  before_action :new_breadcrumbs, only: [:new, :create]
  before_action :show_breadcrumbs, only: [:edit, :show, :update]
  before_action :load_accounting_periods, only: [:index]

  def index
    @breadcrumbs = [[t(:reversed_vats)]]
    if params[:accounting_period_id]
      session[:accounting_period_id] = params[:accounting_period_id]
      @period = params[:accounting_period_id]
    elsif session[:accounting_period_id]
      @period = session[:accounting_period_id]
    else
      @period = @accounting_periods.last.id
      session[:accounting_period_id] = @period
    end
    @reversed_vats = current_organization.reversed_vats.where('accounting_period_id=?', @period).order('id')
    @reversed_vats = @reversed_vats.page(params[:page]).decorate
  end

  def new
    @accounting_period = current_organization.accounting_periods.find(session[:accounting_period_id])
    @reversed_vat = @accounting_period.next_reversed_vat
  end

  def show
    @reversed_vat_reports = @reversed_vat.reversed_vat_reports.page(params[:page])
  end

  def edit
    @reversed_vat_reports = @reversed_vat.reversed_vat_reports.page(params[:page])
  end

  def create
    @reversed_vat = ReversedVat.new(reversed_vat_params)
    @reversed_vat.organization = current_organization
    respond_to do |format|
      if @reversed_vat.save
        format.html { redirect_to reversed_vats_path, notice: "#{t(:reversed_vat)} #{t(:was_successfully_created)}" }
      else
        @accounting_period = current_organization.accounting_periods.find(session[:accounting_period_id])
        @reversed_vat = @accounting_period.next_reversed_vat
        flash.now[:danger] = "#{t(:failed_to_create)} #{t(:reversed_vat)}"
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @reversed_vat.update(reversed_vat_period_params)
        format.html { redirect_to reversed_vats_path, notice: "#{t(:reversed_vat)} #{t(:was_successfully_updated)}" }
      else
        @reversed_vat_reports = @reversed_vat.reversed_vat_reports.page(params[:page])
        flash.now[:danger] = "#{t(:failed_to_update)} #{t(:reversed_vat)}"
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @reversed_vat.destroy
    respond_to do |format|
      format.html { redirect_to reversed_vats_path, notice: "#{t(:reversed_vat)} #{t(:was_successfully_deleted)}" }
    end
  end

  def state_change
    @reversed_vat = current_organization.reversed_vats.find(params[:id])
    authorize! :manage, @reverse_vat
    if @reversed_vat.state_change(params[:event], DateTime.now, current_user.id)
      msg_h = { notice: t(:success) }
    else
      msg_h = { alert: t(:fail) }
    end
    redirect_to reversed_vats_path, msg_h
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def reversed_vat_params
    params.require(:reversed_vat).permit(:name, :vat_from, :vat_to, :accounting_period_id, :deadline)
  end

  def new_breadcrumbs
    @breadcrumbs = [[t(:reversed_vats), reversed_vats_path], ["#{t(:new)} #{t(:reversed_vat)}"]]
  end

  def show_breadcrumbs
    @breadcrumbs = [[t(:reversed_vats), reversed_vats_path], [@reversed_vat.name]]
  end

  def load_accounting_periods
    @accounting_periods = current_organization.accounting_periods.order('id')
    if @accounting_periods.size == 0
      redirect_to helps_show_message_path(message: "#{I18n.t(:accounting_period)} #{I18n.t(:missing)}")
    end
  end
end

app/views/reversed_vats/_form.html.haml
%div
  = simple_form_for(@reversed_vat, wrapper: :horizontal_form, html: {class: 'form-horizontal'}) do |f|
    = f.error_notification
    = f.association :accounting_period, as: :hidden
    .form-group
      .labels_width.control-label
        = f.label :accounting_period
      .fields_width
        %input{id: 'show', type: 'text', class: 'form-control', value: f.object.accounting_period.name, disabled: true}

    = f.input :name, disabled: !@reversed_vat.preliminary?
    = f.input :vat_from, as: :string, :input_html => { :class => 'date', :value => localize(f.object.vat_from, :format => "%Y-%m-%d"), :readonly => 'readonly'}
    = f.input :vat_to, as: :string, :input_html => { :class => 'date', :value => localize(f.object.vat_to, :format => "%Y-%m-%d"), :readonly => 'readonly'}
    = f.input :deadline, as: :string, :input_html => { :class => 'date', :value => localize(f.object.deadline, :format => "%Y-%m-%d"), :readonly => 'readonly'}
    = f.input :state, disabled: true
    - if @reversed_vat.calculated?
      = f.input :calculated_at, as: :string, :input_html => { :class => 'date', :value => localize(f.object.calculated_at, :format => "%Y-%m-%d"), :readonly => 'readonly'}
    - if @reversed_vat.reported?
      = f.input :reported_at, as: :string, :input_html => { :class => 'date', :value => localize(f.object.reported_at, :format => "%Y-%m-%d"), :readonly => 'readonly'}

    .form-button-group
      .actions
        - if @reversed_vat.new_record? || @reversed_vat.preliminary?
          = f.submit class: 'btn btn-primary'
        - if !@reversed_vat.new_record? && @reversed_vat.can_calculate?
          - url = state_change_reversed_vat_path + '&event=mark_calculated'
          = link_to "#{t(:calculate)}", url, method: 'post', class: 'btn btn-primary'
        - if !@reversed_vat.new_record? && @reversed_vat.can_report?
          - url = state_change_reversed_vat_path + '&event=mark_reported'
          = link_to "#{t(:report)}", url, method: 'post', class: 'btn btn-primary'
  - if @reversed_vat_reports
    = render partial: 'reversed_vat_reports/list', locals: {reversed_vat_reports: @reversed_vat_reports}

app/views/reversed_vats/edit.html.haml
= render 'form'

app/views/reversed_vats/index.html.haml
.input-group.col-sm-48
  = link_to "#{t(:create)} #{t(:reversed_vat)}", new_reversed_vat_path, class: 'btn btn-success'

  .col-sm-30.col-md-30.pull-right.text-right
    = form_tag reversed_vats_path, class: 'form-inline submit-on-change', method: :get, enforce_utf8: false  do
      = text_field_tag('locale' , params[:locale], type:'hidden')
      = select_tag(:accounting_period_id,
        options_for_select(@accounting_periods.each.collect{|w| [w.name, w.id]}, @period),
        class: 'btn btn-default')
.clear &nbsp;

.table-responsive
  %table{:class => 'table table-striped'}
    %thead
      %tr
        %th= t(:name)
        %th.numeric= t(:from)
        %th.numeric= t(:to)
        %th.numeric= t(:deadline)
        %th= t(:state)
        %th
        %th
    %tbody
      - @reversed_vats.each do |reversed_vat|
        %tr
          %td= reversed_vat.name
          %td.numeric= reversed_vat.vat_from
          %td.numeric= reversed_vat.vat_to
          %td.numeric= reversed_vat.deadline
          %td= reversed_vat.state
          %td.numeric= link_to settings_icon, edit_reversed_vat_path(reversed_vat)
          %td.numeric= delete_modal reversed_vat, nil, '#mdId'

  = paginate @reversed_vats, :theme => 'twitter-bootstrap-3'

= render partial: 'shared/modal_deletes', locals: {modalId: 'mdId'}

app/views/reversed_vats/new.html.haml
= render 'form'

app/views/reversed_vats/show.html.haml
= render 'form'