config/routes.rb
require 'resque/server'
Emmy::Application.routes.draw do
  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'

  mount Resque::Server.new, at: "/resque"

  root 'pages#start'
  devise_for :users, controllers: {sessions: 'user_sessions'}
  [:about, :start, :formats, :test].each do |p|
    get "/#{p}", to: "pages##{p}"
  end

  namespace :admin do
    resources :organizations
    resources :users do
      member do
        patch 'update_roles', as: :update_roles
      end
    end
    get 'dashboard', to: 'dashboard#index'
    constraints lambda { |request| request.env['warden'].authenticate? && request.env['warden'].user.superadmin? } do
      mount Resque::Server.new, at: "resque"
    end
  end

  get "organization_selector", to: "dashboard#organization_selector"
  get ':organization_slug', to: 'organizations#show', as: 'organization'
  patch ':organization_slug', to: 'organizations#update'
  scope ':organization_slug' do
    get "dashboard", to: "dashboard#index"

    resources :accounting_periods

    resources :accounting_plans do
      post 'disable_accounts', as: :disable_accounts
      resources :accounting_groups
      resources :accounting_classes
      resources :accounts do
        post 'toggle_active', as: :toggle_active
      end
    end
    get 'accounts_receivables', to: 'accounts_receivables#index', as: 'accounts_receivables'
    get 'accounts_payables', to: 'accounts_payables#index', as: 'accounts_payables'
    resources :batches
    resources :closing_balances do
      resources :closing_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :comments
    resources :contact_relations
    resources :contacts
    resources :conversions do
      delete 'clear'
    end
    resources :customers do
      collection do
        get 'name_search', as: :name_search
        get 'city_search', as: :city_search
      end
    end
    resources :default_codes
    resources :default_code_headers
    resources :documents
    resources :employees
    resources :export_bank_files
    resources :economics_wizard do
      collection do
        get 'start'
        get 'stop'
      end
    end
    resources :export_bank_file_rows
    get 'helps/show_help'
    get 'helps/show_chapter_help'
    get 'helps/show_message'
    resources :import_bank_files do
      resources :import_bank_file_rows do
        get 'match_verificate', as: :match_verificate
        get 'set_verificate', as: :set_verificate
        get 'set_template_verificate', as: :set_template_verificate
      end
    end
    resources :import_batches, only: [:new, :create]
    resources :imports do
      resources :import_batches, only: [:new, :create]
      member do
        post 'state_change', as: :state_change
        get 'new_purchase', as: :new_purchase
        post 'create_purchase', as: :create_pruchase
      end
    end
    resources :ink_code_headers
    resources :ink_codes
    resources :inventories do
      resources :inventory_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :items
    resources :ledgers do
      resources :ledger_accounts
    end
    resources :ledger_transactions
    resources :manuals
    resources :mail_templates
    resources :materials
    resources :ne_code_headers
    resources :ne_codes
    resources :opening_balances do
      post 'create_from_ub'
      resources :opening_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :production_batches, only: [:new, :create]
    resources :productions do
      resources :production_batches, only: [:new, :create]
      resources :materials
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :purchases do
      resources :purchase_items
      member do
        post 'state_change', as: :state_change
      end
      post 'single_purchase', as: :single_purchase
    end

    get 'reports/order_verificates_report'
    get 'reports/order_ledger_report'
    get 'reports/order_result_report'
    get 'reports/order_balance_report'
    get 'reports/sale_statistics'
    post 'reports/verificates'
    post 'reports/ledger'
    post 'reports/result_report'
    post 'reports/balance_report'

    resources :result_units

    resources :reversed_vats do
      resources :reversed_vat_reports
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :sales do
      resources :sale_items
      member do
        post 'state_change', as: :state_change
        post 'send_email', as: :send_email
        post 'send_reminder_email', as: :send_reminder_email
        post 'regenerate_invoice', as: :regenerate_invoice
      end
      collection do
        get 'invoice_search', as: :invoice_search
      end
    end
    get 'statistics/index'
    resources :shelves

    resources :sie_exports
    resources :sie_imports

    resources :simplified_sales

    resources :suppliers

    resources :stock_values do
      resources :stock_value_items
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :tax_code_headers
    resources :tax_codes

    resources :tax_returns do
      resources :tax_return_reports
      member do
        post 'state_change', as: :state_change
      end
    end

    resources :tax_tables do
      resources :tax_table_rows
    end

    post 'templates_import', to: 'templates#import', as: 'templates_import'
    resources :templates do
      resources :template_items
    end

    resources :transfers do
      member do
        post 'send_package', as: :send_package
        post 'receive_package', as: :receive_package
      end
    end
    resources :units
    resources :users do
      member do
        patch :update_roles, as: :update_roles
      end
    end
    resources :vat_periods do
      resources :vat_reports
      member do
        post 'state_change', as: :state_change
      end
    end
    resources :vats
    resources :verificates do
      resources :verificate_items
      member do
        post 'state_change', as: :state_change
        post 'reversal', as: :reversal
        post 'add_verificate_items', as: :add_verificate_items
      end
    end
    resources :wage_periods do
      resources :wages
      resources :wage_reports
      member do
        post 'state_change', as: :state_change
        post 'create_wage', as: :create_wage
      end
    end
    resources :wages_wizard do
      collection do
        get 'start'
        get 'stop'
      end
    end
    resources :warehouses
  end

end

app/models/report.rb
class Report
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  def initialize(accounting_period)
    @accounting_period = accounting_period
  end

  attr_accessor :accounting_period, :result_unit

  TYPES = ['pdf', 'list']

  def report_type
  end

  def persisted?
    false
  end
end

app/models/statistics/report.rb
module Statistics
  class Report
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  respond_to :html, :json, :pdf
  before_action :load_accounting_period, only: [:order_verificates_report,
                                                :order_ledger_report,
                                                :order_result_report,
                                                :order_balance_report]
  before_action :load_verificates, only: [:verificates]

  def order_verificates_report
    @breadcrumbs = [["#{t(:verificates)} #{t(:list)}"]]
    @report = Report.new @accounting_period
    @accounting_periods = current_organization.accounting_periods
  end

  def verificates
    @verificates = @verificates.decorate
    respond_to do |format|
      format.pdf do
        render(pdf: 'verificates', template: 'reports/verificates', layout: 'pdf')
      end
      format.html
    end
  end

  def order_ledger_report
    @breadcrumbs = [["#{t(:ledger)} #{t(:report)}"]]
    @report = Report.new @accounting_period
    @accounting_periods = current_organization.accounting_periods
  end

  def ledger
    @report = Report.new params[:report][:accounting_period]    
    @accounting_period = current_organization.accounting_periods.find(@report.accounting_period)

    if params[:report][:report_type] == 'list'
      redirect_to ledger_ledger_accounts_path(@accounting_period.ledger)
      return
    end

    @ledger_accounts = current_organization.ledger_accounts
                           .where('accounting_period_id = ?', @report.accounting_period)
                           .sort_by { |ledger_account| ledger_account.account_number }

    # @verificate_items = VerificateItem
    # .joins(:verificate, :account)
    # .where("verificate_items.organization_id = ? AND verificate_items.accounting_period_id = ? AND verificates.state = 'final'", current_organization.id, @accounting_period.id)
    # .select('accounts.number AS num','accounts.description AS desc', "SUM(debit) AS deb", "SUM(credit) AS cre")
    # .group('accounts.number', 'accounts.description')
    # .order('accounts.number')

    respond_to do |format|
      format.pdf do
        render(pdf: 'ledger', template: 'reports/ledger', layout: 'pdf')
      end
      format.html
    end
  end

  def order_result_report
    @breadcrumbs = [["#{t(:result)} #{t(:report)}"]]
    @report = Report.new @accounting_period
    @accounting_periods = current_organization.accounting_periods
    @result_unit = current_organization.result_units
  end

  def result_report
    @report = Report.new params[:report][:accounting_period]
    result_unit_id = params[:report][:result_unit]
    if !result_unit_id.blank?
      @result_unit = current_organization.result_units.find(result_unit_id)
    end
    @accounting_period = current_organization.accounting_periods.find(@report.accounting_period)
    if result_unit_id.blank?
      @verificate_items = VerificateItem
      .joins(:verificate, :account => :accounting_class)
      .where("verificate_items.organization_id = ? AND verificate_items.accounting_period_id = ? AND verificates.state = 'final' AND accounts.number > 2999 ", current_organization.id, @accounting_period.id)
      .select('accounting_classes.number AS cls', 'accounting_classes.name AS cls_dsc', 'accounts.number AS num','accounts.description AS desc', "SUM(debit) AS deb", "SUM(credit) AS cre")
      .group('accounting_classes.number', 'accounting_classes.name', 'accounts.number', 'accounts.description')
      .order('accounts.number')
    else
      @verificate_items = VerificateItem
      .joins(:verificate, :account => :accounting_class)
      .where("verificate_items.organization_id = ? AND verificate_items.accounting_period_id = ? AND verificate_items.result_unit_id = ?  AND verificates.state = 'final' AND accounts.number > 2999 ", current_organization.id, @accounting_period.id, result_unit_id)
      .select('accounting_classes.number AS cls', 'accounting_classes.name AS cls_dsc', 'accounts.number AS num','accounts.description AS desc', "SUM(debit) AS deb", "SUM(credit) AS cre")
      .group('accounting_classes.number', 'accounting_classes.name', 'accounts.number', 'accounts.description')
      .order('accounts.number')
    end  
    respond_to do |format|
      format.pdf do
        render(pdf: 'result', template: 'reports/result', layout: 'pdf')
      end
      format.html
    end
  end

  def order_balance_report
    @breadcrumbs = [["#{t(:balance)} #{t(:report)}"]]
    @report = Report.new @accounting_period
    @accounting_periods = current_organization.accounting_periods
  end

  def balance_report
  # OBS maste plocka bort verificate som inte är final
    @report = Report.new params[:report][:accounting_period]
    @accounting_period = current_organization.accounting_periods.find(@report.accounting_period)

    ib = "(select sum(debit-credit)
           from opening_balance_items
           where opening_balance_items.accounting_period_id = #{@accounting_period.id} and
                 opening_balance_items.account_id = accounts.id)"

    ver = "(select sum(debit-credit)
            from verificate_items INNER JOIN verificates ON verificate_items.verificate_id = verificates.id
            where verificate_items.accounting_period_id = #{@accounting_period.id} AND
                  verificate_items.account_id = accounts.id AND
                  verificates.state = 'final')"

    @verificate_items = Account
    .joins("INNER JOIN accounting_classes ON accounting_classes.id = accounts.accounting_class_id")
    .select("accounts.number as acc,
             accounts.description as desc,
             accounting_classes.number as cls,
             accounting_classes.name as cls_desc,
             #{ib} as ib,
             #{ver} as ver")
    .where("accounts.number < '2999'")
    .order('accounts.number')

    respond_to do |format|
      format.pdf do
        render(pdf: 'balance', template: 'reports/balance', layout: 'pdf')
      end
      format.html
    end
  end

  def vat_report
    @report = Report.new(params[:from_short_date], params[:to_short_date])
    @accounting_period = AccountingPeriod.find(params[:report][:accounting_period].to_i)
    @sale_items = VerificateItem
    .joins(:verificate, :account => :accounting_group)
    .where("verificate_items.organization_id = ? AND verificate_items.accounting_period_id = ? AND verificates.state = 'final' AND accounting_groups.number > '30' AND accounting_groups.number < '35' AND verificates.posting_date > ? AND verificates.posting_date < ? ", current_organization.id, @accounting_period.id, params[:from_short_date], params[:to_short_date])
    .select('accounts.number AS num','accounts.description AS desc', "SUM(debit) AS deb", "SUM(credit) AS cre")
    .group('accounts.number', 'accounts.description')
    .order('accounts.number')

    @verificate_items = VerificateItem
    .joins(:verificate, :account => [:accounting_class, :accounting_group])
    .where("verificate_items.organization_id = ? AND verificate_items.accounting_period_id = ? AND verificates.state = 'final' AND accounting_groups.number = '26' ", current_organization.id, @accounting_period.id)
    .select('accounting_classes.number AS cls', 'accounting_classes.name AS cls_dsc', 'accounts.number AS num','accounts.description AS desc', "SUM(debit) AS deb", "SUM(credit) AS cre")
    .group('accounting_classes.number', 'accounting_classes.name', 'accounts.number', 'accounts.description')
    .order('accounts.number')

    respond_to do |format|
      format.pdf do
        render(pdf: 'vat_report', template: 'reports/vat_report', layout: 'pdf')
      end
      format.html
    end
  end

  def sale_statistics
    @breadcrumbs = [[t(:sale_statistics)]]
    # Statistics::SaleStat.from_params will return early if params[..].blank?
    @sale_stats = Statistics::SaleStat.list_from_params(current_organization,
                                                   params[:newer_than],
                                                   params[:older_than])
    @sale_stat_sum = Statistics::SaleStat.as_sumarized(@sale_stats)
    respond_to do |format|
      format.html
    end
  end

  private

  def load_accounting_period
    @accounting_period = current_organization.accounting_periods.where('active = true').first
    unless @accounting_period
      redirect_to helps_show_message_path(message: "#{I18n.t(:accounting_period)} #{I18n.t(:missing)}")
    end
  end

  def load_verificates
    @report = Report.new params[:report][:accounting_period]
    @accounting_period = current_organization.accounting_periods.find(@report.accounting_period)
    @verificates = current_organization.verificates
                       .where("accounting_period_id = ? AND state = 'final'", @accounting_period.id)
                       .order(:number)
    if @verificates.size == 0
      redirect_to helps_show_message_path(message: "#{I18n.t(:verificates)} #{I18n.t(:missing)}")
    end
  end
end

app/views/reports/balance.pdf.haml
- save_class = ''
%table.table.table-striped
  %tr
    %td{colspan: '5'}
      .pull-left
        %h2= t(:balance)
      .pull-right
        %h2= @accounting_period.name
  %tr
    - @verificate_items.each do |item|
      - if !item.ver.nil? || !item.ib.nil?
        - if save_class != item.cls
          - save_class = item.cls
          %tr.filler
            %td{colspan:'5'} &nbsp;
          %tr
            %th{colspan: '2'}=item.cls_desc
            %th.numeric= t(:ib)
            %th.numeric= t(:change)
            %th.numeric= t(:ub)

        - ver = item.ver.nil? ? 0 : item.ver
        - ib = item.ib.nil? ? 0 : item.ib
        - sum = ib + ver
        %tr
          %td.short=item.acc
          %td= item.desc
          %td.numeric= item.ib
          %td.numeric= item.ver
          %td.numeric= sum

app/views/reports/ledger.pdf.haml
%table.table.table-striped
  %tr
    %td{colspan: '3'}
      .pull-left
        %h2= t(:ledger)
      .pull-right
        %h2= @accounting_period.name
  %tr
    %th.main= t(:account)
    %th= t(:description)
    %th.numeric= t(:sum)

  - @ledger_accounts.each do |ledger_account|
    %tr
      %td.main=ledger_account.account_number
      %td=ledger_account.account_text
      %td.numeric=ledger_account.sum

app/views/reports/order_balance_report.html.haml
= simple_form_for(@report, wrapper: :horizontal_form, html: {class: 'form-horizontal', target: "_blank" }, url: reports_balance_report_path(report_id: 0, format: 'pdf')) do |f|
  = f.error_notification
  = f.input :accounting_period, as: :select, collection: @accounting_periods, include_blank: false, selected: @accounting_period.id

  .form-button-group
    .actions
      = f.submit class: 'btn btn-primary'

app/views/reports/order_ledger_report.html.haml
= simple_form_for(@report, wrapper: :horizontal_form, html: {class: 'form-horizontal', target: "_blank" }, url: reports_ledger_path(report_id: 0, format: 'pdf')) do |f|
  = f.error_notification
  = f.input :accounting_period, as: :select, collection: @accounting_periods, include_blank: false, selected: @accounting_period.id
  = f.input :report_type, as: :select, collection: Report::TYPES, include_blank: false, input_html: {class: 'short'}

  .form-button-group
    .actions
      = f.submit class: 'btn btn-primary'

:javascript
  $(document).ready(function() {
    $("#report_report_type").change(function() {
      val = $('#report_report_type').val();
      if (val == 'list') {
        $(this).closest('form').removeAttr('target');
      }
      else {
        $(this).closest('form').attr('target', '_blank');
      };
    });
  });

app/views/reports/order_result_report.html.haml
= simple_form_for(@report, wrapper: :horizontal_form, html: {class: 'form-horizontal', target: "_blank" }, url: reports_result_report_path(report_id: 0, format: 'pdf')) do |f|
  = f.error_notification
  = f.input :accounting_period, as: :select, collection: @accounting_periods, include_blank: false, selected: @accounting_period.id
  = f.input :result_unit, as: :select, collection: @result_unit

  .form-button-group
    .actions
      = f.submit class: 'btn btn-primary'

app/views/reports/order_verificates_report.html.haml
= simple_form_for(@report, wrapper: :horizontal_form, html: {class: 'form-horizontal', target: "_blank" }, url: reports_verificates_path(report_id: 0, format: 'pdf')) do |f|
  = f.error_notification
  = f.input :accounting_period, as: :select, collection: @accounting_periods, include_blank: false, selected: @accounting_period.id

  .form-button-group
    .actions
      = f.submit class: 'btn btn-primary'

app/views/reports/result.pdf.haml
- save_class = ''
- total = 0.00
%table.table.table-striped
  %tr
    %td{colspan: '3'}
      .pull-left
        %h2= t(:result)
        - if @result_unit
          %h3= @result_unit.name
      .pull-right
        %h2= @accounting_period.name
  - @verificate_items.each do |item|
    - if save_class != item.cls
      - save_class = item.cls
      %tr.filler
        %td  &nbsp;
      %tr
        %th=item.cls
        %th.nowrap= item.cls_dsc
        %th
    %tr
      - item.deb = 0 if item.deb == nil
      - item.cre = 0 if item.cre == nil
      - sum = -item.deb + item.cre
      - total += sum
      %td=item.num
      %td=item.desc
      %td.numeric=sum
  %tr.filler
    %td  &nbsp;
  %tr
    %th
    %th= t(:result)
    %th.numeric=total

app/views/reports/sale_statistics.html.haml
.row
  .col-sm-40.col-md-40.pull-right.text-right
    = form_tag reports_sale_statistics_path, class: 'form-inline submit-on-change', method: :get, enforce_utf8: false do
      = text_field_tag('locale' , params[:locale], type:'hidden')

      = select_tag(:newer_than,
        options_for_select(months_list, params[:newer_than]),
        class: 'btn btn-default',
        prompt: "#{t(:filter)} #{t(:newer_than)}: #{t(:all)}")

      = select_tag(:older_than,
        options_for_select(months_list, params[:older_than]),
        class: 'btn btn-default',
        prompt: "#{t(:filter)} #{t(:older_than)}: #{t(:all)}")

.table-responsive
  %table{:class => 'table table-striped'}
    %thead
      %tr
        %th= t(:warehouse)
        %th= t(:num_sales)
        %th= t(:batch)
        %th= t(:num_pkg)
        %th= t(:sum_amount)
    %tbody
      - @sale_stats.each do |sale_stat|
        %tr
          %td= link_to sale_stat.warehouse.name, warehouse_path(sale_stat.warehouse)
          %td= sale_stat.num_sales
          %td= sale_stat.batch_names
          %td= sale_stat.num_pkg
          %td= as_sek(sale_stat.sum_amount)

    %tfoot
      %tr
        %th= t(:sum)
        %th= @sale_stat_sum.num_sales
        %th= @sale_stat_sum.batch_names
        %th= @sale_stat_sum.num_pkg
        %th= as_sek(@sale_stat_sum.sum_amount)

app/views/reports/verificates.pdf.haml
%table.table.table-striped
  %tr
    %td{colspan: '4'}
      .pull-left
        %h2= t(:verificates)
      .pull-right
        %h2= @verificates.first.accounting_period.name
  - @verificates.each do |ver|
    %tr
      %th.main= t(:number_the_string) + ": #{ver.number}"
      %th=ver.description
      %th{colspan: '2'}=ver.format_posting_date

    - ver.verificate_items.each do |item|
      %tr
        - item = item.decorate
        %td= item.account_number
        %td= item.description
        %td.numeric= item.debit
        %td.numeric= item.credit
    %tr.filler
      %td{colspan:'4'} &nbsp;